server:
  port: 8080
  contextPath: '/telco-store'

spring:
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/telco'
    username: telco
    password: password
  jpa:
    database-platform: 'com.firstutility.telco.store.jsonb.dialect.JsonPostgreSQLDialect'
    show-sql: true
    hibernate:
      ddl-auto: create

